-- OpenDirector newsletter movement tracker.
--
-- This schema is deliberately isolated from the older SEC/BoardEx tables in
-- public.  Re-running this file is safe.

CREATE SCHEMA IF NOT EXISTS opendirector;

CREATE TABLE IF NOT EXISTS opendirector.newsletters (
    gmail_message_id TEXT PRIMARY KEY,
    gmail_thread_id TEXT,
    subject TEXT NOT NULL,
    sender TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    week_ending DATE,
    edition_type TEXT NOT NULL
        CHECK (edition_type IN ('director', 'executive', 'unknown')),
    gmail_labels TEXT[] NOT NULL DEFAULT '{}',
    source_url TEXT NOT NULL,
    raw_text TEXT NOT NULL,
    raw_headers JSONB NOT NULL DEFAULT '{}'::JSONB,
    content_sha256 CHAR(64) NOT NULL,
    parse_version TEXT,
    parse_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (parse_status IN ('pending', 'parsed', 'partial', 'failed')),
    parse_notes JSONB NOT NULL DEFAULT '[]'::JSONB,
    first_ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS newsletters_received_at_idx
    ON opendirector.newsletters (received_at DESC);
CREATE INDEX IF NOT EXISTS newsletters_week_ending_idx
    ON opendirector.newsletters (week_ending DESC);
CREATE INDEX IF NOT EXISTS newsletters_parse_status_idx
    ON opendirector.newsletters (parse_status);

CREATE TABLE IF NOT EXISTS opendirector.movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gmail_message_id TEXT NOT NULL
        REFERENCES opendirector.newsletters(gmail_message_id)
        ON DELETE CASCADE,
    event_index INTEGER NOT NULL,
    person_name TEXT NOT NULL,
    organization_name TEXT,
    role_title TEXT,
    movement_type TEXT NOT NULL
        CHECK (movement_type IN (
            'appointment',
            'departure',
            'retirement',
            'transition',
            'acting',
            'unknown'
        )),
    effective_date DATE,
    announcement_text TEXT NOT NULL,
    context_text TEXT,
    predecessor_name TEXT,
    successor_name TEXT,
    person_url TEXT,
    organization_url TEXT,
    linkedin_url TEXT,
    extraction_method TEXT NOT NULL,
    extraction_confidence NUMERIC(4, 3) NOT NULL
        CHECK (extraction_confidence BETWEEN 0 AND 1),
    needs_review BOOLEAN NOT NULL DEFAULT TRUE,
    review_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (review_status IN ('pending', 'reviewed', 'rejected')),
    review_notes TEXT,
    manual_override BOOLEAN NOT NULL DEFAULT FALSE,
    raw_block TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (gmail_message_id, event_index)
);

CREATE INDEX IF NOT EXISTS movements_person_name_idx
    ON opendirector.movements (lower(person_name));
CREATE INDEX IF NOT EXISTS movements_organization_name_idx
    ON opendirector.movements (lower(organization_name));
CREATE INDEX IF NOT EXISTS movements_effective_date_idx
    ON opendirector.movements (effective_date DESC);
CREATE INDEX IF NOT EXISTS movements_type_idx
    ON opendirector.movements (movement_type);
CREATE INDEX IF NOT EXISTS movements_review_idx
    ON opendirector.movements (review_status, needs_review);

CREATE TABLE IF NOT EXISTS opendirector.ingestion_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    source TEXT NOT NULL,
    parse_version TEXT NOT NULL,
    messages_seen INTEGER NOT NULL DEFAULT 0,
    messages_loaded INTEGER NOT NULL DEFAULT 0,
    movements_loaded INTEGER NOT NULL DEFAULT 0,
    messages_partial INTEGER NOT NULL DEFAULT 0,
    messages_failed INTEGER NOT NULL DEFAULT 0,
    notes JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE OR REPLACE VIEW opendirector.movement_timeline AS
SELECT
    m.id,
    m.person_name,
    m.organization_name,
    m.role_title,
    m.movement_type,
    m.effective_date,
    n.week_ending,
    n.received_at AS announcement_received_at,
    n.edition_type,
    m.announcement_text,
    m.context_text,
    m.predecessor_name,
    m.successor_name,
    m.extraction_confidence,
    m.needs_review,
    m.review_status,
    n.source_url
FROM opendirector.movements AS m
JOIN opendirector.newsletters AS n USING (gmail_message_id);

CREATE OR REPLACE VIEW opendirector.review_queue AS
SELECT *
FROM opendirector.movement_timeline
WHERE needs_review
  AND review_status = 'pending'
ORDER BY announcement_received_at DESC, id;

CREATE OR REPLACE VIEW opendirector.upcoming_movements AS
SELECT *
FROM opendirector.movement_timeline
WHERE effective_date >= CURRENT_DATE
  AND movement_type IN ('appointment', 'departure', 'retirement', 'transition')
ORDER BY effective_date, organization_name, person_name;

CREATE OR REPLACE VIEW opendirector.company_activity AS
SELECT
    organization_name,
    count(*) AS movement_count,
    count(*) FILTER (WHERE movement_type = 'appointment') AS appointments,
    count(*) FILTER (
        WHERE movement_type IN ('departure', 'retirement')
    ) AS departures,
    min(COALESCE(effective_date, week_ending)) AS first_movement_date,
    max(COALESCE(effective_date, week_ending)) AS latest_movement_date
FROM opendirector.movement_timeline
WHERE organization_name IS NOT NULL
GROUP BY organization_name;

-- ASX security mappings and daily market data. These tables are source-labelled
-- so a research feed can later be replaced or compared with licensed ASX data.

CREATE TABLE IF NOT EXISTS opendirector.market_securities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange TEXT NOT NULL DEFAULT 'ASX',
    exchange_code TEXT NOT NULL,
    issuer_name TEXT NOT NULL,
    instrument_type TEXT NOT NULL DEFAULT 'ordinary_share',
    currency CHAR(3) NOT NULL DEFAULT 'AUD',
    provider TEXT NOT NULL,
    provider_symbol TEXT NOT NULL,
    valid_from DATE NOT NULL DEFAULT DATE '1900-01-01',
    valid_to DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (valid_to IS NULL OR valid_to >= valid_from),
    UNIQUE (provider, provider_symbol, valid_from)
);

CREATE INDEX IF NOT EXISTS market_securities_exchange_code_idx
    ON opendirector.market_securities (exchange, exchange_code);
CREATE UNIQUE INDEX IF NOT EXISTS market_securities_current_provider_symbol_idx
    ON opendirector.market_securities (provider, provider_symbol)
    WHERE valid_to IS NULL;

CREATE TABLE IF NOT EXISTS opendirector.organization_security_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name TEXT NOT NULL,
    security_id BIGINT NOT NULL
        REFERENCES opendirector.market_securities(id)
        ON DELETE CASCADE,
    valid_from DATE NOT NULL DEFAULT DATE '1900-01-01',
    valid_to DATE,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    mapping_method TEXT NOT NULL,
    mapping_confidence NUMERIC(4, 3) NOT NULL
        CHECK (mapping_confidence BETWEEN 0 AND 1),
    review_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (review_status IN ('pending', 'confirmed', 'rejected')),
    review_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (valid_to IS NULL OR valid_to >= valid_from),
    UNIQUE (organization_name, security_id, valid_from)
);

CREATE INDEX IF NOT EXISTS organization_security_name_idx
    ON opendirector.organization_security_matches (lower(organization_name));
CREATE UNIQUE INDEX IF NOT EXISTS organization_security_current_primary_idx
    ON opendirector.organization_security_matches (lower(organization_name))
    WHERE is_primary
      AND valid_to IS NULL
      AND review_status = 'confirmed';

CREATE TABLE IF NOT EXISTS opendirector.daily_prices (
    security_id BIGINT NOT NULL
        REFERENCES opendirector.market_securities(id)
        ON DELETE CASCADE,
    price_date DATE NOT NULL,
    open_price NUMERIC(18, 6),
    high_price NUMERIC(18, 6),
    low_price NUMERIC(18, 6),
    close_price NUMERIC(18, 6) NOT NULL,
    adjusted_close NUMERIC(18, 6),
    volume BIGINT,
    dividend NUMERIC(18, 8),
    split_ratio NUMERIC(18, 8),
    currency CHAR(3) NOT NULL,
    source TEXT NOT NULL,
    source_symbol TEXT NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (volume IS NULL OR volume >= 0),
    PRIMARY KEY (security_id, price_date, source)
);

CREATE INDEX IF NOT EXISTS daily_prices_date_idx
    ON opendirector.daily_prices (price_date DESC);

CREATE TABLE IF NOT EXISTS opendirector.price_ingestion_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    requested_start DATE NOT NULL,
    requested_end DATE NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'completed', 'partial', 'failed')),
    securities_requested INTEGER NOT NULL DEFAULT 0,
    securities_loaded INTEGER NOT NULL DEFAULT 0,
    rows_upserted INTEGER NOT NULL DEFAULT 0,
    failures INTEGER NOT NULL DEFAULT 0,
    notes JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS opendirector.price_ingestion_failures (
    run_id BIGINT NOT NULL
        REFERENCES opendirector.price_ingestion_runs(id)
        ON DELETE CASCADE,
    security_id BIGINT
        REFERENCES opendirector.market_securities(id)
        ON DELETE SET NULL,
    provider_symbol TEXT NOT NULL,
    failure_message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (run_id, provider_symbol)
);

CREATE OR REPLACE VIEW opendirector.price_coverage AS
SELECT
    s.id AS security_id,
    s.exchange,
    s.exchange_code,
    s.issuer_name,
    s.provider,
    s.provider_symbol,
    count(p.*) AS observation_count,
    min(p.price_date) AS first_price_date,
    max(p.price_date) AS latest_price_date
FROM opendirector.market_securities AS s
LEFT JOIN opendirector.daily_prices AS p
    ON p.security_id = s.id
GROUP BY
    s.id,
    s.exchange,
    s.exchange_code,
    s.issuer_name,
    s.provider,
    s.provider_symbol;

CREATE OR REPLACE VIEW opendirector.movement_security_links AS
SELECT
    timeline.*,
    security.id AS security_id,
    security.exchange,
    security.exchange_code,
    security.provider,
    security.provider_symbol,
    match.mapping_confidence
FROM opendirector.movement_timeline AS timeline
JOIN opendirector.organization_security_matches AS match
    ON lower(match.organization_name) = lower(timeline.organization_name)
JOIN opendirector.market_securities AS security
    ON security.id = match.security_id
WHERE match.review_status = 'confirmed'
  AND match.is_primary
  AND COALESCE(timeline.effective_date, timeline.week_ending)
      >= match.valid_from
  AND (
      match.valid_to IS NULL
      OR COALESCE(timeline.effective_date, timeline.week_ending)
          <= match.valid_to
  );
